import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>FAQ Accordion</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='text-red-500'>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Impedit animi
        illo deserunt! Placeat doloremque obcaecati dicta delectus consectetur
        fuga optio aliquam cum dolorum perferendis totam mollitia, aperiam
        officia eos? Quis!
      </main>
    </div>
  )
}
